### ISSUE TITLE
Tooltip text as the same color from background

### ISSUE THREAD

**Issue by furansa** [dracula/qt5#5]
Tooltip text have the same color from background, so it's not possible to read on both active or inactive windows.

Active window example on Qutebrowser:

![screenshot_20220211_220506](https://user-images.githubusercontent.com/15025555/153677437-7d638342-14fa-4768-a691-d224cfe6d7f7.png)

Inactive window example on Qutebrowser:

![screenshot_20220211_220521](https://user-images.githubusercontent.com/15025555/153677552-6b8f0ca2-cd52-4d25-b53f-088d0697a17d.png)

Example on VirtualBox:

![screenshot_20220211_220645](https://user-images.githubusercontent.com/15025555/153677630-ba8a21a5-bc22-4f4a-a575-b48083f79ed1.png)

Qt5ct:

![screenshot_20220211_220903](https://user-images.githubusercontent.com/15025555/153677664-894abef3-2000-4071-8bd2-a70e04b657b0.png)

**Comment by furansa** [comment]
Here's the PR with the fix: https://github.com/dracula/qt5/pull/6

**Comment by TechieAndroid** [comment]
Thanks man I merged it! :)
